services:
  - type: "pserv"
    name: "kitchen-kontrol-db"
    plan: "starter"
    region: "oregon"
    databaseName: "kitchendb"
    databaseUser: "kitchenuser"

  - type: "web"
    name: "kitchen-kontrol-backend"
    runtime: "docker"
    plan: "starter"
    branch: "main"
    dockerfilePath: "Dockerfile.server"
    region: "oregon"
    envVars:
      - key: "NODE_ENV"
        value: "production"
      - key: "PORT"
        value: "3002"
      - key: "DATABASE_URL"
        fromDatabase:
          name: "kitchen-kontrol-db"
          property: "connectionString"

  - type: "web"
    name: "kitchen-kontrol-frontend"
    runtime: "static"
    branch: "main"
    buildCommand: "npm run build"
    staticPublishPath: "build"
    envVars:
      - key: "REACT_APP_API_URL"
        fromService:
          type: "web"
          name: "kitchen-kontrol-backend"
          property: "host"
