services:
  - type: "pserv"
    name: "kitchen-kontrol-db"
    plan: "starter"
    region: "oregon"

  - type: "web"
    name: "kitchen-kontrol-backend"
    env: "docker"
    plan: "starter"
    buildCommand: ""
    startCommand: "node server.js"
    preDeployCommand: "npm run migrate:up && npm run seed:pg"
    branch: "main"
    dockerfilePath: "Dockerfile.server"
    region: "oregon"
    envVars:
      - key: "NODE_ENV"
        value: "production"
      - key: "PORT"
        value: "3002"
      - key: "DATABASE_URL"
        fromDatabase:
          name: "kitchen-kontrol-db"
          property: "connectionString"

  - type: "web"
    name: "kitchen-kontrol-frontend"
    env: "static"
    branch: "main"
    buildCommand: "npm run build"
    staticPublishPath: "build"
    region: "oregon"
    envVars:
      - key: "REACT_APP_API_URL"
        fromService:
          type: "web"
          name: "kitchen-kontrol-backend"
          property: "host"
