services:
  - type: "web"
    name: "kitchen-kontrol-backend"
    runtime: "docker"
    plan: "starter"
    branch: "main"
    dockerfilePath: "Dockerfile.server"
    region: "oregon"
    envVars:
      - key: "NODE_ENV"
        value: "production"
      - key: "PORT"
        value: "3002"

  - type: "web"
    name: "kitchen-kontrol-frontend"
    runtime: "static"
    branch: "main"
    buildCommand: "npm run build"
    staticPublishPath: "build"
    envVars:
      - key: "REACT_APP_API_URL"
        fromService:
          type: "web"
          name: "kitchen-kontrol-backend"
          property: "host"
